name: abc_xyz
copyright: 2021 Mark Eggenstein
description: A new Flutter project.
publish_to: 'none'

#        1.2.3+BuildNumber
version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
